let voiceChannel=null, localStream=null, voicePeers=new Map(), voiceUsers=new Map();
window.addEventListener("jaszcweb:voice", async e=>{await openVoiceChannel(e.detail.id);});

async function openVoiceChannel(channelId){
 if(voiceChannel){try{await voiceChannel.untrack();}catch{} await JC.sb.removeChannel(voiceChannel);voiceChannel=null;}
 cleanupVoicePeers();
 const {data:channel}=await JC.sb.from("channels").select("*").eq("id",channelId).single();if(!channel)return;
 const panel=document.getElementById("voicePanel");panel.innerHTML=`<div class="voice-shell"><div><div class="eyebrow">VOICE CHANNEL</div><h2>🔊 ${escapeHTML(channel.name)}</h2><p>${escapeHTML(channel.topic||"Hang out and talk.")}</p></div><div id="voiceParticipants" class="voice-participants"></div><div class="voice-actions"><button class="btn primary" id="joinVoiceBtn">Join voice</button><button class="btn danger hidden" id="leaveVoiceBtn">Leave voice</button><button class="btn secondary hidden" id="muteVoiceBtn">Mute</button></div><div id="voiceStatus" class="voice-status">Not connected.</div></div>`;
 document.getElementById("joinVoiceBtn").onclick=()=>joinVoice(channelId); document.getElementById("leaveVoiceBtn").onclick=leaveVoice; document.getElementById("muteVoiceBtn").onclick=toggleMute;
}

async function joinVoice(channelId){
 if(voiceChannel)return;
 try{localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:false});}catch(e){alert("Microphone permission is required for voice chat.");return;}
 voiceChannel=JC.sb.channel(`voice:${channelId}`,{config:{private:true,presence:{key:JC.user.id}}});
 voiceChannel.on("presence",{event:"sync"},syncVoiceParticipants).on("presence",{event:"join"},syncVoiceParticipants).on("presence",{event:"leave"},syncVoiceParticipants).on("broadcast",{event:"signal"},handleSignal);
 voiceChannel.subscribe(async status=>{if(status==="SUBSCRIBED"){await voiceChannel.track({user_id:JC.user.id,name:JC.profile?.display_name||"User"});document.getElementById("joinVoiceBtn").classList.add("hidden");document.getElementById("leaveVoiceBtn").classList.remove("hidden");document.getElementById("muteVoiceBtn").classList.remove("hidden");document.getElementById("voiceStatus").textContent="Connected.";syncVoiceParticipants();}});
}

async function syncVoiceParticipants(){if(!voiceChannel)return;const state=voiceChannel.presenceState();const current=new Set();Object.values(state).flat().forEach(p=>{if(p.user_id&&p.user_id!==JC.user.id){current.add(p.user_id);voiceUsers.set(p.user_id,p);if(JC.user.id < p.user_id)ensurePeer(p.user_id,p.name,true);}});for(const id of voicePeers.keys()){if(!current.has(id)){voicePeers.get(id).pc.close();voicePeers.delete(id);document.getElementById(`audio-${id}`)?.remove();}}const box=document.getElementById("voiceParticipants");box.innerHTML=`<div class="voice-me">🟢 ${escapeHTML(JC.profile?.display_name||"You")} (you)</div>`+Array.from(voiceUsers.entries()).filter(([id])=>current.has(id)).map(([id,p])=>`<div class="voice-user">🟢 ${escapeHTML(p.name||"User")}</div>`).join("");}

async function ensurePeer(peerId,peerName,initiator=false){if(voicePeers.has(peerId))return voicePeers.get(peerId);const pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});localStream?.getTracks().forEach(t=>pc.addTrack(t,localStream));pc.onicecandidate=e=>{if(e.candidate)sendVoiceSignal(peerId,{type:"ice",candidate:e.candidate});};pc.ontrack=e=>{let audio=document.getElementById(`audio-${peerId}`);if(!audio){audio=document.createElement("audio");audio.id=`audio-${peerId}`;audio.autoplay=true;audio.playsInline=true;document.body.appendChild(audio);}audio.srcObject=e.streams[0];};voicePeers.set(peerId,{pc,name:peerName});if(initiator){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await sendVoiceSignal(peerId,{type:"offer",sdp:offer});}return voicePeers.get(peerId);}
async function handleSignal({payload}){const from=payload.from;if(!from||from===JC.user.id||payload.to&&payload.to!==JC.user.id)return;const s=payload.data;const peer=await ensurePeer(from,payload.name||"User",false);if(s.type==="offer"){await peer.pc.setRemoteDescription(s.sdp);const answer=await peer.pc.createAnswer();await peer.pc.setLocalDescription(answer);await sendVoiceSignal(from,{type:"answer",sdp:answer});}else if(s.type==="answer"){await peer.pc.setRemoteDescription(s.sdp);}else if(s.type==="ice"&&s.candidate){try{await peer.pc.addIceCandidate(s.candidate);}catch{}}}
async function sendVoiceSignal(target,data){if(!voiceChannel)return;await voiceChannel.send({type:"broadcast",event:"signal",payload:{from:JC.user.id,name:JC.profile?.display_name||"User",to:target,data}});}
function cleanupVoicePeers(){voicePeers.forEach(({pc})=>pc.close());voicePeers.clear();document.querySelectorAll("audio[id^='audio-']").forEach(x=>x.remove());}
async function leaveVoice(){if(voiceChannel){try{await voiceChannel.untrack();}catch{}await JC.sb.removeChannel(voiceChannel);voiceChannel=null;}localStream?.getTracks().forEach(t=>t.stop());localStream=null;cleanupVoicePeers();document.getElementById("joinVoiceBtn")?.classList.remove("hidden");document.getElementById("leaveVoiceBtn")?.classList.add("hidden");document.getElementById("muteVoiceBtn")?.classList.add("hidden");document.getElementById("voiceStatus").textContent="Disconnected.";}
function toggleMute(){if(!localStream)return;const track=localStream.getAudioTracks()[0];track.enabled=!track.enabled;document.getElementById("muteVoiceBtn").textContent=track.enabled?"Mute":"Unmute";}
